config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'

  resources :movies do
    resources :characters
  end

  resources :characters

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_movie, only: [:new, :create, :show]
  before_action :set_character, only: [:show]

  def index
    # come in from a nested we will have a params[:movie_id]
    if params[:movie_id]
      set_movie
      @characters = @movie.characters
    else
      @characters = Character.all
    end
  end
  
  def new
    @character = @movie.characters.build
  end

  def create
    @character = @movie.characters.build(character_params)

    if @character.save
      redirect_to movie_characters_path(@movie)
    else
      render :new
    end
  end

  def show
  end
  
  private
    def set_movie
      @movie = Movie.find_by_id(params[:movie_id])
    end

    def set_character
      @character = Character.find_by_id(params[:id])
    end

    def character_params
      params.require(:character).permit(:name, :race, :gender)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :duration, :genre, :release_date)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/characters/index.html.erb
<% if @movie %>
  <h1><%= @movie.title %> Characters</h1>
<% else %>
  <h1>All Characters</h1>
<% end %>

<ul>
  <% @characters.each do |character| %>
    <li><%= link_to character.name, movie_character_path(@movie, character) %></li>
  <% end %>
</ul>

app/views/characters/new.html.erb
<h1>Create Character for <%= @movie.title %></h1>

<%= form_for([@movie, @character]) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :race %>
    <%= f.text_field :race %>
  </div>
  <div>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <%= f.submit "Create Character" %>
<% end %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>
<p>Plays in <%= @movie.title %></p>

app/views/layouts/_nav.html.erb
<nav>
  <ul>
    <li><%= link_to "View Movies", movies_path %></li>
    <li><%= link_to "Create Movie", new_movie_path %></li>
    <li><%= link_to 'View Characters', characters_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieCharactersSg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Duration</th>
      <th>Genre</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.release_date %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @movie.duration %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>

 |
<%= link_to 'View Characters', movie_characters_path(@movie) %> |
<%= link_to 'Create Character', new_movie_character_path(@movie) %> |
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>